# docker-compose.yml
services:
  maria:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restpointdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - restbackend

  backend:
    build:
      context: .   # changed from ./server
      dockerfile: Dockerfile
    container_name: backend_container
    restart: unless-stopped
    env_file:
      - .env       # changed from ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - maria
    networks:
      - restbackend

volumes:
  mariadb_data:

networks:
  restbackend:
    driver: bridge
