version: "3.9"  # Specify Compose file version

services:
  maria:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restpointdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - restbackend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_container
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - maria
    networks:
      - restbackend

# Volumes for persistent storage
volumes:
  mariadb_data:

# Custom networks
networks:
  restbackend:
    driver: bridge
